// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Whether this Rust library was compiled for the Wcash chain
/// (cargo feature `wcash`). App bootstrap asserts this matches the Dart
/// `VIZOR_CHAIN` define so a mixed-flavor build fails fast instead of
/// signing transactions in the wrong chain domain.
bool isWcashBuild() => RustLib.instance.api.crateApiSimpleIsWcashBuild();

/// Keep wallet consensus parameters aligned with the local Ironwood regtest
/// node. Production builds leave the default activation-at-height-1 behavior.
Future<void> configureRegtestIronwoodActivationHeight({required int height}) =>
    RustLib.instance.api.crateApiSimpleConfigureRegtestIronwoodActivationHeight(
      height: height,
    );

/// Enables Regtest-speed migration timing on Testnet only. Mainnet and
/// Regtest consensus behavior are unaffected.
Future<void> configureFastTestnetMigration({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiSimpleConfigureFastTestnetMigration(enabled: enabled);
